export const data={
    "jdList": [
      {
        "jobRole": "iOS Developer",
        "companyName": "Tech Innovators",
        "location": "Remote",
        "minJdSalary": 15,
        "maxJdSalary": 30,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.techinnovators.com/jobs/ios-developer"
      },
      {
        "jobRole": "Backend Developer",
        "companyName": "Cloud Solutions",
        "location": "Bangalore",
        "minJdSalary": 26,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.cloudsolutions.com/jobs/backend-developer"
      },
      {
        "jobRole": "Android Developer",
        "companyName": "Mobile Masters",
        "location": "Chennai",
        "minJdSalary": 18,
        "maxJdSalary": 35,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.mobilemasters.com/jobs/android-developer"
      },
      {
        "jobRole": "Full Stack Developer",
        "companyName": "InnovateX",
        "location": "Delhi NCR",
        "minJdSalary": 20,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.innovatex.com/jobs/full-stack-developer"
      },
      {
        "jobRole": "Frontend Developer",
        "companyName": "Web Wizards",
        "location": "Remote",
        "minJdSalary": 22,
        "maxJdSalary": 45,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.webwizards.com/jobs/frontend-developer"
      },
      {
        "jobRole": "Data Scientist",
        "companyName": "Data Insights",
        "location": "Bangalore",
        "minJdSalary": 30,
        "maxJdSalary": 60,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.datainsights.com/jobs/data-scientist"
      },
      {
        "jobRole": "UX Designer",
        "companyName": "Creative Minds",
        "location": "Chennai",
        "minJdSalary": 18,
        "maxJdSalary": 36,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.creativeminds.com/jobs/ux-designer"
      },
      {
        "jobRole": "DevOps Engineer",
        "companyName": "CloudOps",
        "location": "Delhi NCR",
        "minJdSalary": 25,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.cloudops.com/jobs/devops-engineer"
      },
      {
        "jobRole": "Project Manager",
        "companyName": "Tech Solutions",
        "location": "Remote",
        "minJdSalary": 28,
        "maxJdSalary": 55,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 6,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.techsolutions.com/jobs/project-manager"
      },
      {
        "jobRole": "QA Engineer",
        "companyName": "Quality Matters",
        "location": "Bangalore",
        "minJdSalary": 18,
        "maxJdSalary": 34,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.qualitymatters.com/jobs/qa-engineer"
      },
      {
        "jobRole": "iOS Developer",
        "companyName": "Mobile Innovators",
        "location": "Bangalore",
        "minJdSalary": 30,
        "maxJdSalary": 45,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.mobileinnovators.com/jobs/ios-developer"
      },
      {
        "jobRole": "Android Developer",
        "companyName": "NextGen Mobile",
        "location": "Remote",
        "minJdSalary": 25,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.nextgenmobile.com/jobs/android-developer"
      },
      {
        "jobRole": "Data Analyst",
        "companyName": "DataPros",
        "location": "Delhi NCR",
        "minJdSalary": 20,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.datapros.com/jobs/data-analyst"
      },
      {
        "jobRole": "Full Stack Developer",
        "companyName": "WebExperts",
        "location": "Chennai",
        "minJdSalary": 30,
        "maxJdSalary": 60,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.webexperts.com/jobs/full-stack-developer"
      },
      {
        "jobRole": "DevOps Engineer",
        "companyName": "InfraTech",
        "location": "Remote",
        "minJdSalary": 27,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.infratech.com/jobs/devops-engineer"
      },
      {
        "jobRole": "Machine Learning Engineer",
        "companyName": "AI Pioneers",
        "location": "Delhi NCR",
        "minJdSalary": 35,
        "maxJdSalary": 70,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.aipioneers.com/jobs/machine-learning-engineer"
      },
      {
        "jobRole": "Product Manager",
        "companyName": "Product Gurus",
        "location": "Bangalore",
        "minJdSalary": 30,
        "maxJdSalary": 60,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 6,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.productgurus.com/jobs/product-manager"
      },
      {
        "jobRole": "iOS Developer",
        "companyName": "App Creators",
        "location": "Chennai",
        "minJdSalary": 25,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.appcreators.com/jobs/ios-developer"
      },
      {
        "jobRole": "Frontend Developer",
        "companyName": "Web Creators",
        "location": "Remote",
        "minJdSalary": 20,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.webcreators.com/jobs/frontend-developer"
      },
      {
        "jobRole": "Backend Developer",
        "companyName": "CodeCrafters",
        "location": "Bangalore",
        "minJdSalary": 26,
        "maxJdSalary": 55,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.codecrafters.com/jobs/backend-developer"
      },
      {
        "jobRole": "Android Developer",
        "companyName": "Mobile Apps",
        "location": "Delhi NCR",
        "minJdSalary": 20,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.mobileapps.com/jobs/android-developer"
      },
      {
        "jobRole": "Data Scientist",
        "companyName": "Data Visionaries",
        "location": "Remote",
        "minJdSalary": 40,
        "maxJdSalary": 80,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.datavisionaries.com/jobs/data-scientist"
      },
      {
        "jobRole": "QA Engineer",
        "companyName": "Quality Coders",
        "location": "Chennai",
        "minJdSalary": 18,
        "maxJdSalary": 35,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.qualitycoders.com/jobs/qa-engineer"
      },
      {
        "jobRole": "iOS Developer",
        "companyName": "Innovative Apps",
        "location": "Bangalore",
        "minJdSalary": 30,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.innovativeapps.com/jobs/ios-developer"
      },
      {
        "jobRole": "Backend Developer",
        "companyName": "Server Solutions",
        "location": "Remote",
        "minJdSalary": 25,
        "maxJdSalary": 45,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.serversolutions.com/jobs/backend-developer"
      },
      {
        "jobRole": "Data Analyst",
        "companyName": "Data Wizards",
        "location": "Delhi NCR",
        "minJdSalary": 22,
        "maxJdSalary": 45,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.datawizards.com/jobs/data-analyst"
      },
      {
        "jobRole": "Frontend Developer",
        "companyName": "Creative Web",
        "location": "Bangalore",
        "minJdSalary": 22,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.creativeweb.com/jobs/frontend-developer"
      },
      {
        "jobRole": "Full Stack Developer",
        "companyName": "Tech Innovators",
        "location": "Chennai",
        "minJdSalary": 30,
        "maxJdSalary": 55,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.techinnovators.com/jobs/full-stack-developer"
      },
      {
        "jobRole": "DevOps Engineer",
        "companyName": "Cloud Tech",
        "location": "Remote",
        "minJdSalary": 27,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.cloudtech.com/jobs/devops-engineer"
      },
      {
        "jobRole": "Machine Learning Engineer",
        "companyName": "AI Innovators",
        "location": "Delhi NCR",
        "minJdSalary": 35,
        "maxJdSalary": 70,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.aiinnovators.com/jobs/machine-learning-engineer"
      },
      {
        "jobRole": "Product Manager",
        "companyName": "Innovative Products",
        "location": "Bangalore",
        "minJdSalary": 30,
        "maxJdSalary": 60,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 6,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.innovativeproducts.com/jobs/product-manager"
      },
      {
        "jobRole": "iOS Developer",
        "companyName": "App Developers",
        "location": "Chennai",
        "minJdSalary": 25,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.appdevelopers.com/jobs/ios-developer"
      },
      {
        "jobRole": "Frontend Developer",
        "companyName": "Creative Solutions",
        "location": "Remote",
        "minJdSalary": 20,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 2,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.creativesolutions.com/jobs/frontend-developer"
      },
      {
        "jobRole": "Backend Developer",
        "companyName": "Tech Coders",
        "location": "Bangalore",
        "minJdSalary": 26,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.techcoders.com/jobs/backend-developer"
      },
      {
        "jobRole": "Data Analyst",
        "companyName": "Data Innovators",
        "location": "Delhi NCR",
        "minJdSalary": 22,
        "maxJdSalary": 45,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.datainnovators.com/jobs/data-analyst"
      },
      {
        "jobRole": "Frontend Developer",
        "companyName": "Web Developers",
        "location": "Bangalore",
        "minJdSalary": 22,
        "maxJdSalary": 40,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 3,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.webdevelopers.com/jobs/frontend-developer"
      },
      {
        "jobRole": "Full Stack Developer",
        "companyName": "Innovative Tech",
        "location": "Chennai",
        "minJdSalary": 30,
        "maxJdSalary": 60,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.innovativetech.com/jobs/full-stack-developer"
      },
      {
        "jobRole": "DevOps Engineer",
        "companyName": "Cloud Innovators",
        "location": "Remote",
        "minJdSalary": 27,
        "maxJdSalary": 50,
        "salaryCurrencyCode": "USD",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 4,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.cloudinnovators.com/jobs/devops-engineer"
      },
      {
        "jobRole": "Machine Learning Engineer",
        "companyName": "AI Masters",
        "location": "Delhi NCR",
        "minJdSalary": 35,
        "maxJdSalary": 70,
        "salaryCurrencyCode": "INR",
        "jobDetailsFromCompany": "We are a dynamic and fast-growing technology company specializing in innovative software solutions for the financial services industry. Our team is composed of passionate professionals dedicated to transforming how businesses operate by leveraging cutting-edge technologies like AI, machine learning, and blockchain. As a part of our team, you will work on high-impact projects that drive real-world results, collaborate with a diverse group of experts, and contribute to the development of state-of-the-art products that are shaping the future of finance. We foster a collaborative and inclusive work environment where your ideas are valued and your growth is supported.",
        "minExp": 5,
        "logoUrl": "https://img.freepik.com/free-vector/gradient-logo-with-abstract-shape_23-2148216799.jpg",
        "jdLink": "https://www.aimasters.com/jobs/machine-learning-engineer"
      }
    ]
};